osafe: true
title: "Mitigating Director Gender Bias in Movie Recommender Systems"
source: .
destination: _site
url: "https://michael-garciaperez.github.io"
baseurl: "/DSC180B-Capstone-Project"
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
